-- Legacy column additions for databases created before columns were merged into CREATE TABLE.
-- Idempotent on Postgres (IF NOT EXISTS). SQLite uses 001_legacy_columns.sqlite.sql.

ALTER TABLE users ADD COLUMN IF NOT EXISTS default_reminder_minutes INTEGER DEFAULT 30;
ALTER TABLE users ADD COLUMN IF NOT EXISTS daily_digest_enabled INTEGER DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS daily_digest_time TEXT DEFAULT '08:00';
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_digest_sent TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS weekly_report_enabled INTEGER DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_weekly_report TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'USD';
ALTER TABLE users ADD COLUMN IF NOT EXISTS budget_cycle_start INTEGER DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS spending_alert_pct INTEGER DEFAULT 80;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bill_due_alert_days INTEGER DEFAULT 3;
ALTER TABLE users ADD COLUMN IF NOT EXISTS plan TEXT DEFAULT 'free';
ALTER TABLE users ADD COLUMN IF NOT EXISTS trial_ends_at TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS stripe_customer_id TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS stripe_subscription_id TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS segment TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS billing_interval TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS country TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS language TEXT DEFAULT 'en';
ALTER TABLE users ADD COLUMN IF NOT EXISTS birth_date TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS gender TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS billing_period_start TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS billing_period_end TEXT DEFAULT '';

ALTER TABLE transactions ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'USD';
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS attachment_path TEXT DEFAULT '';

ALTER TABLE notes ADD COLUMN IF NOT EXISTS is_journal INTEGER DEFAULT 0;
ALTER TABLE notes ADD COLUMN IF NOT EXISTS entry_date TEXT DEFAULT '';

ALTER TABLE waitlist ADD COLUMN IF NOT EXISTS approve_token TEXT DEFAULT '';

ALTER TABLE user_preferences ADD COLUMN IF NOT EXISTS life_priorities TEXT DEFAULT '';
ALTER TABLE user_preferences ADD COLUMN IF NOT EXISTS life_priorities_set INTEGER DEFAULT 0;

ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS summary TEXT DEFAULT '';
ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS summary_message_count INTEGER DEFAULT 0;

ALTER TABLE user_memory ADD COLUMN IF NOT EXISTS confidence REAL DEFAULT 1.0;
