/* eslint-disable react/no-unescaped-entities -- legal copy with many quoted terms */
import { SiteNav, NavBackLink } from "@/components/site-nav";

export default function TermsPage() {
  return (
    <div className="flex flex-col flex-1 bg-black text-white">
    <SiteNav>
      <NavBackLink />
    </SiteNav>
    <div className="flex-1 max-w-2xl mx-auto px-4 py-12 w-full">
      <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>
      <div className="prose prose-invert prose-sm max-w-none">
        <p className="text-white/40 text-xs mb-6">Effective Date: May 12, 2026 | Version 3.0</p>
        
        <div className="bg-zinc-900 border border-white/10 rounded-xl p-6 mb-8">
          <p className="text-sm text-white/80">
            <strong>IMPORTANT NOTICE:</strong> PLEASE READ THESE TERMS OF SERVICE CAREFULLY. BY ACCESSING, USING, REGISTERING FOR, OR CONTINUING TO USE ORRYON (THE "SERVICE"), YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE LEGALLY BOUND BY THESE TERMS OF SERVICE, INCLUDING ALL DISCLAIMERS, LIMITATIONS OF LIABILITY, INDEMNIFICATION OBLIGATIONS, BINDING ARBITRATION AGREEMENT, AND CLASS ACTION WAIVER. IF YOU DO NOT AGREE TO THESE TERMS, DO NOT ACCESS, USE, REGISTER FOR, OR CONTINUE USING THE SERVICE.
          </p>
        </div>

        <h2 className="text-xl font-semibold mt-8 mb-3">1. Definitions</h2>
        <p>For purposes of these Terms of Service, the following terms have the meanings set forth below. Capitalized terms not otherwise defined herein have the meanings ascribed to them in the Privacy Policy or elsewhere in these Terms.</p>
        <p><strong>"Affiliate"</strong> means any entity that directly or indirectly controls, is controlled by, or is under common control with Orryon, where "control" means ownership of more than fifty percent (50%) of the voting securities or equivalent voting interest.</p>
        <p><strong>"Content"</strong> means all text, data, information, software, graphics, audio, video, images, photographs, trademarks, logos, and other materials made available by or through the Service, including all AI-generated outputs, forecasts, budgets, suggestions, recommendations, and wellness guidance.</p>
        <p><strong>"Effective Date"</strong> means the date first set forth above.</p>
        <p><strong>"Feedback"</strong> means any comments, suggestions, ideas, or other feedback provided by you to Orryon regarding the Service.</p>
        <p><strong>"Intellectual Property Rights"</strong> means all patents, copyrights, trademarks, trade secrets, database rights, moral rights, and all other intellectual property or proprietary rights, whether registered or unregistered.</p>
        <p><strong>"Orryon," "we," "us," or "our"</strong> means Orryon, its Affiliates, and their respective officers, directors, employees, agents, licensors, and successors.</p>
        <p><strong>"Privacy Policy"</strong> means Orryon's Privacy Policy, as amended from time to time, which is incorporated herein by reference.</p>
        <p><strong>"Service"</strong> means the Orryon platform and all related websites, applications, features, Content, and services, including AI chat, financial tracking, budgeting, goal setting, breathing and meditation exercises, scheduling, and any beta or experimental features.</p>
        <p><strong>"Terms"</strong> means these Terms of Service, including all exhibits, schedules, and amendments.</p>
        <p><strong>"User," "you," or "your"</strong> means the individual or entity accessing or using the Service, including any authorized users of an organization account.</p>
        <p><strong>"User Content"</strong> means any data, information, Content, or materials submitted, uploaded, transmitted, or otherwise provided by you to the Service, including financial records, notes, goals, chat messages, and Feedback.</p>

        <h2 className="text-xl font-semibold mt-8 mb-3">2. Electronic Acceptance, Clickwrap Consent, and Eligibility</h2>
        <p>These Terms constitute a legally binding agreement between you and Orryon. Your access to or use of the Service constitutes your acceptance of these Terms. If you do not agree, you must immediately cease all use of the Service. By clicking "I Agree," "Sign Up," "Create Account," or any similar button, or by accessing or using the Service, you affirmatively consent to these Terms and the Privacy Policy. You represent and warrant that: (a) you are at least eighteen (18) years of age and have full legal capacity to enter into these Terms; (b) you are not located in, and will not access the Service from, any country or territory embargoed by the United States or on any U.S. Office of Foreign Assets Control ("OFAC") sanctioned or restricted party list; (c) you will comply with all applicable laws, rules, and regulations; and (d) if you are using the Service on behalf of an organization, you have the authority to bind that organization to these Terms. Any use of the Service by anyone under the age of eighteen (18) is strictly prohibited.</p>

        <h2 className="text-xl font-semibold mt-8 mb-3">3. Description of Service and Modifications</h2>
        <p>Orryon is a Life OS platform — personal finance, organization, AI concierge, and wellness in one place. The Service may include, without limitation, transaction tracking, budgeting tools, goal setting, AI-powered chat assistance (including third-party large language models such as xAI), breathing and meditation exercises, scheduling, notifications, data export, and related features. We reserve the right, at any time and in our sole discretion, to modify, suspend, discontinue, or terminate the Service or any feature thereof, temporarily or permanently, with or without notice, and without liability to you or any third party. Continued use of the Service after any modification constitutes acceptance of the modified Service.</p>

        <h2 className="text-xl font-semibold mt-8 mb-3">4. Not Professional Advice; Assumption of Risk; Multiple Disclaimers</h2>
        <p><strong>ORRYON IS NOT A FINANCIAL ADVISOR, LAWYER, ACCOUNTANT, TAX ADVISOR, DOCTOR, THERAPIST, PSYCHOLOGIST, OR ANY OTHER LICENSED OR CERTIFIED PROFESSIONAL.</strong> All Content, forecasts, budgets, suggestions, projections, AI responses, wellness recommendations, breathing exercises, meditation guidance, and any other output, whether generated by Orryon, its Affiliates, or third-party providers, is provided solely for informational, organizational, educational, and general wellness purposes and does not constitute professional, financial, legal, medical, mental health, or any other form of advice. <strong>NOTWITHSTANDING ANYTHING TO THE CONTRARY IN THESE TERMS OR THE PRIVACY POLICY, YOU ACKNOWLEDGE AND AGREE THAT:</strong> (I) YOU USE THE SERVICE AND ALL CONTENT ENTIRELY AT YOUR OWN RISK; (II) YOU SHALL NOT MAKE ANY FINANCIAL, LEGAL, MEDICAL, MENTAL HEALTH, OR OTHER IMPORTANT DECISIONS BASED SOLELY ON THE SERVICE OR ANY CONTENT; (III) THE BREATHE AND MEDITATION FEATURES ARE NOT MEDICAL TREATMENT, THERAPY, DIAGNOSIS, OR A SUBSTITUTE FOR PROFESSIONAL HEALTHCARE; (IV) IF YOU HAVE ANY MEDICAL, MENTAL HEALTH, OR OTHER CONDITION, YOU WILL CONSULT A QUALIFIED HEALTHCARE PROFESSIONAL BEFORE USING ANY WELLNESS FEATURES; AND (V) ORRYON, ITS AFFILIATES, AND THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AND LICENSORS SHALL HAVE NO LIABILITY WHATSOEVER FOR ANY DECISION, ACTION, INACTION, LOSS, DAMAGE, OR CLAIM ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE OR RELIANCE ON ANY CONTENT. <strong>NOTWITHSTANDING THE FOREGOING OR ANY OTHER PROVISION OF THESE TERMS, THE SERVICE AND ALL CONTENT ARE PROVIDED WITHOUT ANY WARRANTY, REPRESENTATION, OR GUARANTEE OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ACCURACY, COMPLETENESS, RELIABILITY, OR FITNESS FOR ANY PARTICULAR PURPOSE.</strong></p>

        <h2 className="text-xl font-semibold mt-8 mb-3">5. AI Limitations; No Reliance; Additional Disclaimers</h2>
        <p>The AI assistant uses third-party large language models (including xAI) and may produce inaccurate, incomplete, biased, hallucinated, outdated, inconsistent, or otherwise unreliable outputs. AI responses do not reflect the views of Orryon and are not verified, endorsed, or warranted by Orryon. <strong>NOTWITHSTANDING ANY OTHER PROVISION OF THESE TERMS, YOU AGREE NOT TO RELY ON ANY AI OUTPUT FOR ANY PURPOSE, ESPECIALLY ANY DECISION WITH MATERIAL FINANCIAL, LEGAL, HEALTH, SAFETY, OR OTHER CONSEQUENCES. ORRYON MAKES NO WARRANTY, REPRESENTATION, OR GUARANTEE REGARDING THE ACCURACY, COMPLETENESS, OR SUITABILITY OF ANY AI OUTPUT. YOU ASSUME ALL RISK ASSOCIATED WITH THE USE OF AI FEATURES.</strong> We reserve the right, at any time and without notice or liability, to modify, limit, suspend, or remove any AI feature or functionality.</p>

        <h2 className="text-xl font-semibold mt-8 mb-3">6. Subscription, Billing, Cancellation, and Refunds</h2>
        <p>New users on monthly plans receive a fourteen (14) day free trial of paid features (annual plans are charged immediately upon signup). After the trial period, continued access requires a paid subscription. Subscriptions automatically renew at the then-current rate unless cancelled in accordance with these Terms. All payments are processed securely by Stripe, Inc.; we do not store full payment card details. Current pricing is displayed at signup and in Settings and is subject to change. To cancel, use the Stripe billing portal via Settings → Manage Billing. Cancellation takes effect at the end of the current billing period. <strong>NOTWITHSTANDING ANY OTHER PROVISION OF THESE TERMS, YOU WILL NOT RECEIVE ANY REFUND, CREDIT, OR PRO-RATA REIMBURSEMENT FOR PARTIAL PERIODS, UNUSED TIME, OR ANNUAL SUBSCRIPTIONS. ANNUAL SUBSCRIPTIONS ARE NON-REFUNDABLE. WE MAY, IN OUR SOLE DISCRETION, OFFER REFUNDS OR CREDITS ON A CASE-BY-CASE BASIS; ANY SUCH OFFER DOES NOT CREATE A RIGHT TO FUTURE REFUNDS OR CONSTITUTE A WAIVER OF THESE TERMS.</strong> If you cancel, your data remains accessible until you delete your account or the account is terminated.</p>

        <h2 className="text-xl font-semibold mt-8 mb-3">7. Intellectual Property Rights</h2>
        <p>The Service and all Content (excluding User Content) are owned by Orryon, its Affiliates, or their respective licensors and are protected by United States and international Intellectual Property Rights laws. Subject to these Terms, Orryon grants you a limited, non-exclusive, non-transferable, revocable, non-sublicensable license to access and use the Service solely for your personal, non-commercial use. <strong>NOTWITHSTANDING ANY OTHER PROVISION, YOU MAY NOT COPY, MODIFY, DISTRIBUTE, SELL, RENT, LEASE, SUBLICENSE, REVERSE ENGINEER, DECOMPILE, DISASSEMBLE, CREATE DERIVATIVE WORKS FROM, OR OTHERWISE EXPLOIT THE SERVICE OR ANY CONTENT WITHOUT OUR PRIOR WRITTEN CONSENT.</strong> All rights not expressly granted are reserved by Orryon and its licensors.</p>

        <h2 className="text-xl font-semibold mt-8 mb-3">8. Acceptable Use Policy</h2>
        <p>You agree not to, and not to permit any third party to: (a) use the Service for any illegal, harmful, fraudulent, abusive, or unauthorized purpose; (b) scrape, crawl, spider, harvest, or otherwise collect data or Content; (c) reverse engineer, decompile, disassemble, or attempt to derive source code; (d) upload, transmit, or store any virus, malware, or harmful code; (e) interfere with or disrupt the Service or servers; (f) attempt to gain unauthorized access; (g) use the AI to generate content that is illegal, abusive, hateful, defamatory, infringing, or violates third-party rights; (h) resell, sublicense, or provide the Service to third parties; (i) use the Service to train or improve any AI model without prior written permission; or (j) violate any applicable law or third-party right. We may suspend or terminate your account for any violation, in our sole discretion, without notice or refund.</p>

        <h2 className="text-xl font-semibold mt-8 mb-3">8.1 Fair Usage Policy</h2>
        <p>Certain subscription tiers (including Premium and Premium Plus) advertise "unlimited" features, including without limitation unlimited chat messages, subject at all times to this Fair Usage Policy ("Policy"). "Unlimited" is a marketing term and does not mean infinite, unrestricted, or guaranteed access or performance. All use remains subject to reasonable personal, non-commercial use consistent with typical individual consumption patterns for a single user account. <strong>NOTWITHSTANDING ANY OTHER PROVISION OF THESE TERMS, ORRYON RESERVES THE ABSOLUTE AND SOLE DISCRETION TO DETERMINE, AT ANY TIME AND WITHOUT NOTICE, WHAT CONSTITUTES EXCESSIVE, ABUSIVE, OR NON-COMPLIANT USE UNDER THIS POLICY, INCLUDING BUT NOT LIMITED TO VOLUME, FREQUENCY, PATTERN, AUTOMATION, OR IMPACT ON SERVICE QUALITY OR OTHER USERS.</strong></p>
        <p>Without limiting the foregoing, the following are expressly prohibited and constitute violations of this Policy: (i) any automated, scripted, programmatic, or bot-driven access or queries; (ii) use of the Service for bulk processing, data scraping, crawling, harvesting, indexing, or any commercial data extraction or analysis at scale; (iii) reselling, sublicensing, redistributing, sharing, or providing access to the Service or its outputs to any third party, whether for compensation or otherwise; (iv) generating volumes of requests or outputs that, in our reasonable judgment, degrade, impair, or interfere with the Service's performance, availability, or quality for other users; (v) any use that circumvents, evades, or attempts to evade usage monitoring, rate limiting, or enforcement mechanisms; (vi) use for training, fine-tuning, distilling, or improving any AI, machine learning, or language model, whether proprietary or third-party; or (vii) any other use that we determine, in our sole discretion, is inconsistent with personal, non-commercial use or that abuses the "unlimited" benefit. <strong>NOTWITHSTANDING ANYTHING TO THE CONTRARY, WE MAKE NO WARRANTY, REPRESENTATION, OR GUARANTEE THAT "UNLIMITED" FEATURES WILL BE AVAILABLE, UNINTERRUPTED, ERROR-FREE, OR PERFORM AT ANY PARTICULAR SPEED OR CAPACITY DURING PERIODS OF HIGH DEMAND OR YOUR USE.</strong></p>
        <p>Upon detection or reasonable suspicion of a violation of this Policy, Orryon may, in its sole and absolute discretion and without prior notice, warning, or liability to you: (A) throttle, rate-limit, or temporarily restrict access or functionality; (B) impose hard usage caps or quotas; (C) require an immediate upgrade to a higher tier or contact for enterprise licensing; (D) suspend or terminate your account or access; (E) delete or refuse to process excessive requests or data; and/or (F) pursue any other remedies available under these Terms or applicable law. <strong>NOTWITHSTANDING ANY OTHER PROVISION, YOU SHALL NOT BE ENTITLED TO ANY REFUND, CREDIT, PRO-RATA REIMBURSEMENT, OR DAMAGES ARISING FROM ANY ENFORCEMENT ACTION TAKEN PURSUANT TO THIS POLICY. ALL SUCH ACTIONS ARE FINAL AND NON-APPEALABLE.</strong> This Policy supplements and does not replace the Acceptable Use Policy or any other restrictions in these Terms. Your continued use of any "unlimited" feature constitutes your ongoing acceptance of and agreement to this Policy as amended from time to time.</p>

        <h2 className="text-xl font-semibold mt-8 mb-3">9. User Content and License Grant; No Sale of Data; Third-Party and Security Risks</h2>
        <p><strong>ORRYON DOES NOT SELL USER DATA. WE DO NOT SELL, RENT, LEASE, OR TRADE YOUR PERSONAL INFORMATION OR USER CONTENT TO ANY THIRD PARTY FOR ANY PURPOSE WHATSOEVER.</strong> Your data is used solely to provide, operate, secure, and improve the Service for you—including delivering personalized AI assistance, financial insights, wellness guidance, scheduling, and other features you choose to use. We do not use your User Content for targeted advertising, cross-site tracking, profiling for third parties, or any unrelated commercial purpose.</p>
        <p>You retain all ownership rights in your User Content. You grant Orryon and its Affiliates a worldwide, royalty-free, non-exclusive license to host, store, process, reproduce, and create derivative works from your User Content solely as necessary to operate the Service for your benefit. Any improvement to our AI models or analytics using User Content is performed exclusively on aggregated, anonymized, or de-identified data that cannot identify you as an individual. This license is strictly limited to operational necessity and does not include any right to commercialize, monetize, or exploit your User Content beyond providing the Service to you.</p>
        <p><strong>THIRD-PARTY SERVICES AND SECURITY RISKS; NO LIABILITY.</strong> The Service integrates with and relies upon third-party providers, including without limitation xAI (for AI processing), Stripe (for billing), and other subprocessors and service providers. <strong>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ORRYON SHALL HAVE NO LIABILITY WHATSOEVER—WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, OR OTHERWISE—FOR ANY LOSS, DAMAGE, UNAUTHORIZED ACCESS, DISCLOSURE, ALTERATION, DESTRUCTION, OR MISUSE OF YOUR USER CONTENT OR PERSONAL INFORMATION CAUSED BY, ARISING OUT OF, OR RELATED TO ANY THIRD PARTY, INCLUDING BUT NOT LIMITED TO:</strong> (i) any security breach, data incident, hacking, unauthorized access, or cyberattack at or involving any third-party provider, subprocessor, or infrastructure provider, even if Orryon required commercially reasonable security measures in its contracts with such parties; (ii) any failure, error, omission, downtime, or misconduct by any third-party AI provider (including xAI), payment processor, hosting provider, or other service provider; (iii) any action or inaction by you, including sharing of credentials, phishing, social engineering, or failure to secure your account or devices; (iv) any force majeure event, network failure, or circumstances beyond Orryon's reasonable control; or (v) any other cause not directly and solely attributable to Orryon's gross negligence or willful misconduct.</p>
        <p><strong>NOTWITHSTANDING ANY OTHER PROVISION OF THESE TERMS OR THE PRIVACY POLICY, YOU ACKNOWLEDGE AND AGREE THAT ORRYON USES COMMERCIALLY REASONABLE EFFORTS TO PROTECT YOUR DATA BUT MAKES NO WARRANTY, REPRESENTATION, OR GUARANTEE THAT YOUR DATA WILL BE SECURE, UNINTERRUPTED, OR FREE FROM UNAUTHORIZED ACCESS, AND YOU ASSUME ALL RISK ASSOCIATED WITH THE TRANSMISSION AND STORAGE OF DATA TO OR BY THIRD PARTIES.</strong> Orryon shall have no obligation to notify you of any third-party security incident beyond what is legally required, and any such notification shall not constitute an admission of liability. This section 9 shall survive termination or expiration of these Terms and is in addition to, and not in lieu of, the limitations set forth in section 15 (Limitation of Liability).</p>
        <p>You represent and warrant that you have all rights necessary to grant this license and that your User Content does not violate any law or third-party right. This section shall be construed consistently with our Privacy Policy, which is incorporated by reference.</p>

        <h2 className="text-xl font-semibold mt-8 mb-3">10. Privacy Policy</h2>
        <p>Your use of the Service is subject to our Privacy Policy, which is incorporated herein by reference. By using the Service, you consent to our collection, use, and disclosure of your information as described in the Privacy Policy.</p>

        <h2 className="text-xl font-semibold mt-8 mb-3">11. Third-Party Services and Links</h2>
        <p>The Service integrates with or links to third-party services (including xAI, Stripe, and optional SMTP providers). We are not responsible for any third-party service, its content, availability, or practices. Your use of third-party services is at your own risk and subject to their respective terms and privacy policies.</p>

        <h2 className="text-xl font-semibold mt-8 mb-3">12. Beta and Experimental Features</h2>
        <p>From time to time, we may make available beta, experimental, or pre-release features or services. Such features are provided "AS IS" and "AS AVAILABLE" without warranty of any kind. We may modify, suspend, or discontinue beta features at any time without notice or liability. Your use of beta features is entirely at your own risk.</p>

        <h2 className="text-xl font-semibold mt-8 mb-3">13. Aggregated and Anonymized Data</h2>
        <p>Notwithstanding any other provision, Orryon and its Affiliates may create, use, and disclose aggregated, anonymized, or de-identified data derived from the Service and User Content for analytics, product improvement, research, marketing, and other lawful purposes, provided that such data does not identify you or any individual. You acknowledge that Orryon owns all right, title, and interest in such aggregated and anonymized data.</p>

        <h2 className="text-xl font-semibold mt-8 mb-3">14. Disclaimers; No Warranties; Multiple Repetitions</h2>
        <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICE AND ALL CONTENT ARE PROVIDED "AS IS," "AS AVAILABLE," AND WITHOUT ANY WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, ACCURACY, RELIABILITY, OR THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, OR MEET YOUR REQUIREMENTS. <strong>NOTWITHSTANDING ANY OTHER PROVISION OF THESE TERMS, WE DO NOT WARRANT THAT AI OUTPUTS WILL BE ACCURATE, COMPLETE, OR SUITABLE FOR ANY PURPOSE. YOU ASSUME ALL RISK OF USING THE SERVICE AND ALL CONTENT.</strong> Some jurisdictions do not allow the exclusion of certain warranties; in such cases, the above exclusions shall apply to the maximum extent permitted by law.</p>

        <h2 className="text-xl font-semibold mt-8 mb-3">15. Limitation of Liability; Multiple Repetitions and Notwithstanding Clauses</h2>
        <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ORRYON AND ITS AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AND LICENSORS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, EXEMPLARY, OR OTHER DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, GOODWILL, USE, BUSINESS INTERRUPTION, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR RELATED TO YOUR USE OF (OR INABILITY TO USE) THE SERVICE, ANY CONTENT, AI OUTPUTS, OR THESE TERMS, REGARDLESS OF THE CAUSE OR THEORY OF LIABILITY AND WHETHER OR NOT WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. <strong>NOTWITHSTANDING ANY OTHER PROVISION OF THESE TERMS OR THE PRIVACY POLICY, OUR TOTAL LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATED TO THE SERVICE OR THESE TERMS SHALL NOT EXCEED THE TOTAL AMOUNT YOU PAID TO US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM (OR $0 IF YOU HAVE NOT PAID ANY AMOUNTS). THE FOREGOING LIMITATIONS SHALL APPLY EVEN IF ANY REMEDY FAILS OF ITS ESSENTIAL PURPOSE.</strong> Some jurisdictions do not allow the exclusion or limitation of certain damages; in such cases, our liability shall be limited to the maximum extent permitted by law. <strong>NOTWITHSTANDING THE FOREGOING, NOTHING IN THESE TERMS SHALL LIMIT OR EXCLUDE LIABILITY FOR GROSS NEGLIGENCE, WILLFUL MISCONDUCT, OR FRAUD TO THE EXTENT SUCH LIMITATION OR EXCLUSION IS NOT PERMITTED BY APPLICABLE LAW.</strong></p>

        <h2 className="text-xl font-semibold mt-8 mb-3">16. Indemnification</h2>
        <p>You agree to indemnify, defend, and hold harmless Orryon and its Affiliates, officers, directors, employees, agents, and licensors from and against any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys' fees and costs) arising out of or related to: (a) your use of the Service; (b) your User Content; (c) your violation of these Terms; (d) your violation of any law or third-party right; or (e) any dispute between you and a third party. We reserve the right to assume the exclusive defense and control of any matter subject to indemnification, and you agree to cooperate fully with us.</p>

        <h2 className="text-xl font-semibold mt-8 mb-3">17. Dispute Resolution; Binding Arbitration; Class Action Waiver; Small Claims; Fees; Confidentiality</h2>
        <p><strong>PLEASE READ THIS SECTION CAREFULLY. IT AFFECTS YOUR LEGAL RIGHTS.</strong></p>
        <p>Any dispute, claim, or controversy arising out of or relating to these Terms or the Service shall be resolved exclusively through binding individual arbitration administered by the American Arbitration Association ("AAA") under its Commercial Arbitration Rules, in the State of Wyoming, United States. The arbitration shall be conducted by a single arbitrator. Judgment on the award may be entered in any court having jurisdiction. <strong>NOTWITHSTANDING THE FOREGOING, EITHER PARTY MAY BRING A CLAIM IN SMALL CLAIMS COURT IN WYOMING FOR DISPUTES WITHIN THE JURISDICTIONAL LIMITS OF SUCH COURT, PROVIDED THE CLAIM IS BROUGHT ON AN INDIVIDUAL BASIS.</strong></p>
        <p>YOU AGREE THAT ANY ARBITRATION OR PROCEEDING WILL BE LIMITED TO THE DISPUTE BETWEEN YOU AND ORRYON, AND YOU WAIVE ANY RIGHT TO PARTICIPATE IN A CLASS ACTION, CLASS ARBITRATION, OR OTHER REPRESENTATIVE PROCEEDING. THE ARBITRATOR MAY NOT CONSOLIDATE CLAIMS OR PRESIDE OVER ANY FORM OF REPRESENTATIVE PROCEEDING. <strong>NOTWITHSTANDING ANY OTHER PROVISION, EACH PARTY SHALL BEAR ITS OWN COSTS AND ATTORNEYS' FEES IN CONNECTION WITH ANY ARBITRATION, UNLESS THE ARBITRATOR DETERMINES OTHERWISE IN ACCORDANCE WITH APPLICABLE LAW OR THE AAA RULES. THE ARBITRATOR MAY AWARD FEES AND COSTS TO THE PREVAILING PARTY AS PERMITTED BY LAW.</strong></p>
        <p>All arbitration proceedings, including all documents, testimony, and awards, shall be confidential and shall not be disclosed to any third party except as required by law or to enforce the award. You may opt out of this arbitration agreement by emailing contact@orryon.com within thirty (30) days of first using the Service, stating your intent to opt out. If you do not opt out, this arbitration agreement shall be binding. Nothing in this section prevents either party from seeking injunctive or other equitable relief in a court of competent jurisdiction for Intellectual Property Rights or breach of confidentiality claims. This arbitration agreement shall survive termination of these Terms.</p>

        <h2 className="text-xl font-semibold mt-8 mb-3">18. Governing Law; Jurisdiction; Fallback</h2>
        <p>These Terms shall be governed by and construed in accordance with the laws of the State of Wyoming, without regard to its conflict of laws principles. The United Nations Convention on Contracts for the International Sale of Goods does not apply. <strong>NOTWITHSTANDING THE FOREGOING, IF THE ARBITRATION AGREEMENT IN SECTION 17 IS HELD UNENFORCEABLE OR INAPPLICABLE IN ANY JURISDICTION, THE PARTIES AGREE THAT THE EXCLUSIVE VENUE FOR ANY LEGAL ACTION SHALL BE THE STATE OR FEDERAL COURTS LOCATED IN THE STATE OF DELAWARE, AND EACH PARTY HEREBY CONSENTS TO THE PERSONAL JURISDICTION OF SUCH COURTS.</strong></p>

        <h2 className="text-xl font-semibold mt-8 mb-3">19. Export Controls and Sanctions Compliance</h2>
        <p>You represent and warrant that you are not located in, and will not access the Service from, any country or territory embargoed by the United States or on any OFAC sanctioned or restricted party list. You agree to comply with all applicable export control and sanctions laws and regulations. We reserve the right to suspend or terminate access for any violation of this section without notice or liability.</p>

        <h2 className="text-xl font-semibold mt-8 mb-3">20. DMCA Copyright Policy</h2>
        <p>If you believe that any Content on the Service infringes your copyright, please notify us in writing at the address provided in the Contact section below with the information required by the Digital Millennium Copyright Act (17 U.S.C. § 512). We will respond to notices of alleged copyright infringement in accordance with applicable law.</p>

        <h2 className="text-xl font-semibold mt-8 mb-3">21. Force Majeure</h2>
        <p>Neither party shall be liable for any failure or delay in performing its obligations under these Terms if such failure or delay results from circumstances beyond the reasonable control of that party, including but not limited to acts of God, natural disasters, war, terrorism, riots, embargoes, acts of civil or military authorities, fire, floods, epidemics, pandemics, strikes, or shortages of transportation, facilities, fuel, energy, labor, or materials. The affected party shall give prompt notice and use reasonable efforts to mitigate the effects of the force majeure event.</p>

        <h2 className="text-xl font-semibold mt-8 mb-3">22. Assignment and Successors</h2>
        <p>You may not assign, transfer, or delegate these Terms or any rights or obligations hereunder without our prior written consent. We may freely assign, transfer, or delegate these Terms and our rights and obligations hereunder to any Affiliate or in connection with a merger, acquisition, corporate reorganization, or sale of all or substantially all of our assets. These Terms shall be binding upon and inure to the benefit of the parties and their respective permitted successors and assigns.</p>

        <h2 className="text-xl font-semibold mt-8 mb-3">23. Changes to Terms</h2>
        <p>We may modify these Terms at any time. If we make material changes, we will provide notice by updating the Effective Date, posting a notice in the Service, or sending an email. Your continued use of the Service after the Effective Date of any changes constitutes your acceptance of the modified Terms. If you do not agree, you must stop using the Service.</p>

        <h2 className="text-xl font-semibold mt-8 mb-3">24. Miscellaneous; Severability; Waiver; Entire Agreement; Survival</h2>
        <p>These Terms, together with the Privacy Policy, constitute the entire agreement between you and Orryon concerning the Service and supersede all prior or contemporaneous agreements, representations, and understandings. If any provision of these Terms is held invalid or unenforceable, the remaining provisions shall continue in full force and effect. Our failure to enforce any right or provision shall not constitute a waiver. <strong>NOTWITHSTANDING ANY OTHER PROVISION, SECTIONS 4, 5, 7, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24, AND 25 SHALL SURVIVE TERMINATION OR EXPIRATION OF THESE TERMS.</strong> These Terms do not create any agency, partnership, joint venture, or employment relationship. Headings are for convenience only and shall not affect interpretation.</p>

        <h2 className="text-xl font-semibold mt-8 mb-3">25. Contact Information</h2>
        <p>Questions? Contact us at <a href="mailto:contact@orryon.com" className="underline">contact@orryon.com</a>. For formal legal notices, send to the address provided upon request.</p>

        <div className="mt-12 p-6 bg-zinc-900 border border-white/10 rounded-2xl">
          <p className="text-sm text-white/70">
            BY USING ORRYON, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO THESE TERMS OF SERVICE, INCLUDING THE DISCLAIMERS THAT THIS IS NOT PROFESSIONAL ADVICE, THE LIMITATION OF LIABILITY, THE INDEMNIFICATION OBLIGATION, THE BINDING ARBITRATION AND CLASS ACTION WAIVER, AND ALL OTHER PROVISIONS SET FORTH HEREIN.
          </p>
          <p className="text-xs text-white/40 mt-4">
            This document is not legal advice. Questions or concerns? Contact us at <a href="mailto:contact@orryon.com" className="underline hover:text-white">contact@orryon.com</a>.
          </p>
        </div>
      </div>
    </div>
    </div>
  );
}
